default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("APP_DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("APP_DATABASE_HOST") { '127.0.0.1' } %>

development:
  <<: *default
  database: ekindersys_development

test:
  <<: *default
  database: ekindersys_test

production:
  <<: *default
  database: ekindersys_production
  username: ekindersys